### ISSUE TITLE
Add UTF support

### ISSUE THREAD

**Issue by april** [marumari/decklist#2]
Unicode sucks in PDF... can we make it work?

**Comment by Nightfirecat** [comment]
Like mentioned in #19, this issue is now fixed. (ex: [Lim Dûl's Vault](http://www.decklist.org/?deckmain=1%20Lim-D%C3%BBl%27s%20Vault))

**Comment by tooomm** [comment]
Is this fixed and can be closed?

**Comment by april** [comment]
It's only fixed for some latin characters. I believe there is a very new version of jsPDF that has Unicode support. So I'll likely work on it at some point over the holidays and see if I can make it work.  :)

**Comment by tooomm** [comment]
That are awesome news!

Didn't know it got just partially fixed...

**Comment by Nightfirecat** [comment]
According to MrRio/jsPDF#12, full UTF-8 support is implemented in master, but not yet released. I can confirm that the latest release (1.3.5) does not have working UTF-8 support, so we will need to wait for the next release to address this issue.

**Comment by jangia** [comment]
Is there any info when the next release is coming?

**Comment by Nightfirecat** [comment]
Based on what I found from reading the issues on jsPDF, a beta version was released for 1.4.0 but was found to be buggy. There's been effectively no communication since then, so I don't have that information.

**Comment by april** [comment]
The long wait continues, sorry.  :(

**Comment by arasabbasi** [comment]
We didnt release a buggy beta. ;) We got just very very busy

**Comment by qq645381995** [comment]
等吧

**Comment by Nightfirecat** [comment]
@april jsPDF 1.4.0 has been released: https://github.com/MrRio/jsPDF/releases/tag/v.1.4.0

If I find the time, I'll look at using it in a branch and seeing if it works.

**Comment by april** [comment]
1.4.1 just got released, so that's probably a good place for us to start.

**Comment by april** [comment]
And by us, I mean I'll take a look at this when I can.  :)

**Comment by april** [comment]
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.min.js" integrity="sha384-B3ZwMLt/CqFLkq5omwYXeXs+qquHvXKcwP56Ue+09Fet7TmYmwk/35GWwejM5vWg" crossorigin="anonymous"></script>
```

To save myself some memory space. @arasabbasi, just FYI that your README.md still links to 1.3.6.

**Comment by Nightfirecat** [comment]
I tried dropping it right in and testing locally. It _did_ change the behavior, but it still wasn't the expected "working" behavior. It might require adding in a custom font to work, but I haven't tested that on my end yet.
